version: "3"

services:
  samp:
    image: mrucznik/mrucznik-rp:v2.6
    build: .
    expose:
      - "7777/udp"
    ports:
      - "7777:7777/udp"
    networks:
      - intranet
    depends_on:
      - mysqld

  mysqld:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: samp
    expose:
      - "3306"
    networks:
      intranet:
        aliases:
          - mysqld

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - intranet
    depends_on:
      - mysqld

networks:
  intranet:
    driver: bridge

volumes:
  my-datavolume:
  data:
