version: "3"

services:
  samp:
    image: mrucznik/mrucznik-rp:v2.6
    build: .
    # volumes:
    #   - ./scriptfiles:/root/.samp/runtime/0.3.DL/scriptfiles
    #   - ./mysql.ini:/root/.samp/runtime/0.3.DL/mysql.ini
    #   - ./log-config.yml:/root/.samp/runtime/0.3.DL/log-config.yml
    #   - ./logs:/root/.samp/runtime/0.3.DL/logs
    command: ["server", "run", "--dir", "/samp"]
    expose:
      - "7777/udp"
    ports:
      - "7777:7777/udp"
    environment:
      SAMP_DISCORD_BOT_TOKEN: NjA0NzIwMzk3NTk4MDY0NjUx.XTyEBw.NGrfO3u_0HdE2iUI60IQFQMY_6k
    networks:
      - intranet
    depends_on:
      - mysqld
      # - migrations

  mysqld:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: samp
    expose:
      - "3306"
    networks:
      intranet:
        aliases:
          - mysqld

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - intranet
    depends_on:
      - mysqld

networks:
  intranet:
    driver: bridge

volumes:
  my-datavolume:
  data: